# Generated by Django 6.0.4 on 2026-04-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_posted_at_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='work_setup',
            field=models.TextField(blank=True, null=True),
        ),
    ]
